export {default as AMap} from './AMap';
export {default as Marker} from './Marker';
export {default as InfoWindow} from './InfoWindow';
export {default as PathSimplifier} from './PathSimplifier';
export {default as MassMarks} from './MassMarks';
export {default as Polygon} from './Polygon';
export {default as TileLayerTraffic} from './TileLayerTraffic';
export {default as Polyline} from './Polyline';
export {default as Loca} from './Loca';
